version: '3'

services:
  honeytrap:
    image: honeytrap/honeytrap:latest
    container_name: honeytrap
    ports:
      - "1339:1339"
      - "22:22"
      - "23:23"
      - "80:80"
      - "443:443"
    volumes:
      - ./config.toml:/config/config.toml
    # Keep trying to start HoneyTrap. HoneyTrap will exit when Elastic is not ready.
    # Healthcheck condition in depends_on has been deprecated after version 2.1K
