[listener]
type="socket"

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Enter here the service config

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[channel.console]
type="console"

[channel.elasticsearch]
type="elasticsearch"
url="http://elasticsearch:9200/honeytrap"

[[filter]]
channel=["console", "elasticsearch"]

[[logging]]
output = "stdout"
level = "debug"

